app_principal/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('pokedex/', include('pokedex.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pokedex/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name="pokedex"

urlpatterns = [
    path("listar", listarPokemons, name="listar_pokemons"),
    
    path("pokemon/<int:idpokemon>/", umPokemon , name="um_pokemon")
]

pokedex/models.py
from django.db import models


# Create your models here.
class Categoria(models.Model):
    nome = models.CharField(max_length=120, unique=True)

    def __str__(self):
        return self.nome

    def __int__(self):
        return self.id


class Habilidade(models.Model):
    nome = models.CharField(max_length=120)
    descricao = models.CharField(max_length=200, verbose_name="Descrição/Sobre")

    def __str__(self):
        return self.nome

#
# class Evolucao(models.Model):
#     imagem = models.FileField(upload_to='fotos/')
#     nome = models.CharField(max_length=120)
#     altura = models.FloatField()
#     fk_categoria = models.ForeignKey('Categoria', on_delete=models.PROTECT)
#     fk_habilidades = models.ManyToManyField(Habilidade)
#     ponto_saude = models.PositiveIntegerField()
#     ataque = models.PositiveIntegerField()
#     defesa = models.PositiveIntegerField()
#     ataque_especial = models.PositiveIntegerField()
#     defesa_especial = models.PositiveIntegerField()
#     velocidade = models.PositiveIntegerField()
#
#     def __str__(self):
#         return self.nome


class Pokemon(models.Model):
    imagem = models.FileField(upload_to='fotos/')
    nome = models.CharField(max_length=120)
    altura = models.FloatField()
    fk_categoria = models.ForeignKey('Categoria', on_delete=models.PROTECT)
    fk_habilidades = models.ManyToManyField(Habilidade)
    ponto_saude = models.PositiveIntegerField()
    ataque = models.PositiveIntegerField()
    defesa = models.PositiveIntegerField()
    ataque_especial = models.PositiveIntegerField()
    defesa_especial = models.PositiveIntegerField()
    velocidade = models.PositiveIntegerField()
    evolucao = models.ManyToManyField('Pokemon',null=True, blank=True)

    def __str__(self):
        return self.nome

pokedex/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

def listarPokemons(request):
    pokemons = Pokemon.objects.all()

    contexto = {
        "todos_pokemons": pokemons,
    }
    return render(request, 'listar.html', contexto)


def umPokemon(request, idpokemon=None):
    pokemon = Pokemon.objects.get(id=idpokemon)
    contexto = {
        "pokemon": pokemon,
    }
    return render(request, 'pokemon.html', contexto)

pokedex/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>POKEDEX</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



</head>
<body style= "background-image: url('/anexos/fundo.jpg');" >

<div class="container-fluid mt-5">
    <div class="row">
        <div class="col-md-10 offset-md-1">
            {% block conteudo %}
            {% endblock %}
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

pokedex/templates/listar.html
{% extends "base.html" %}
{% block conteudo %}
    <table class="table table-hover table-dark" >
        <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Altura</th>
            <th>Velocidade</th>
            <th>Categoria</th>
        </tr>
        </thead>
        <tbody>
        {% for objeto in todos_pokemons %}
            <tr scope="row">
                <td><a href="{% url 'pokedex:um_pokemon' idpokemon=objeto.id %}">
                    {{ objeto.id }}</a></td>
                <td>{{ objeto.nome }}</td>
                <td>{{ objeto.altura }}</td>
                <td>{{ objeto.velocidade }}</td>
                <td>{{ objeto.fk_categoria.nome }}{{ objeto.ataque }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

pokedex/templates/pokemon.html
{% extends "base.html" %}
{% block conteudo %}
<div class="row">
    <div class="col-md-6" align="right">
        <a href="{% url 'pokedex:listar_pokemons'  %}">
            <div class="card-header text-white bg-transparent" style="width: 18rem;">
                <img src="{{ pokemon.imagem.url }}" class="card-img-top" alt="...">
                <div class="card-body" align="center">
                    <h5 class="card-title">{{ pokemon.nome }}</h5>
                    <p class="card-text"> Categoria: {{ pokemon.fk_categoria.nome }}</p>
                    <p class="card-text">Ataque: {{ pokemon.ataque }}</p>
                    <p class="card-text">Defesa: {{ pokemon.defesa }}</p>
                    <p class="card-text">Altura: {{ pokemon.altura }}</p>
                    <p class="card-text">Saude: {{ pokemon.ponto_saude }}</p>
                    <p class="card-text">Ataque especial: {{ pokemon.ataque_especial }}</p>
                    <p class="card-text">Defesa especial: {{ pokemon.defesa_especial }}</p>
                    <p class="card-text">velocidade: {{ pokemon.velocidade }}</p>

                </div>
            </div>
        </a>
    </div>

    {% for evolucao in pokemon.evolucao.all %}
    <div class="col-md-6" align="left">
        <a href="{% url 'pokedex:um_pokemon' idpokemon=evolucao.id %}">
            <div class="card-header text-white bg-transparent" style="width: 18rem;">
                <img src="{{ evolucao.imagem.url }}" class="card-img-top" alt="...">
                <div class="card-body" align="center">
                    <h5 class="card-title">{{ evolucao.nome }}</h5>
                    <p class="card-text"> Categoria: {{ evolucao.fk_categoria.nome }}</p>
                    <p class="card-text">Ataque: {{ evolucao.ataque }}</p>
                    <p class="card-text">Defesa: {{ evolucao.defesa }}</p>
                    <p class="card-text">Altura: {{ evolucao.altura }}</p>
                    <p class="card-text">Saude: {{ evolucao.ponto_saude }}</p>
                    <p class="card-text">Ataque especial: {{ evolucao.ataque_especial }}</p>
                    <p class="card-text">Defesa especial: {{ evolucao.defesa_especial }}</p>
                    <p class="card-text">velocidade: {{ evolucao.velocidade }}</p>
                </div>
            </div>
        </a>
    </div>
</div>
{% endfor %}
</div>

<div class="row">
    <div class="col-md-12" align="center">
        <a href="{% url 'pokedex:listar_pokemons' %}">
            <button type="button" class="btn btn-dark">Voltar</button>
        </a>
    </div>
</div>

{% endblock %}